name: Licenses Csharp

on:
  workflow_dispatch:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  licences:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'
      - name: Restore Packages
        run: dotnet restore
        working-directory: ./web/csharp
      - name: Check Licenses
        uses: ONLYOFFICE/check-licenses@v1
        with:
          project_license: Apache-2.0
          working_directory: ./web/csharp
